services:

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8085:80"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "3001:3001"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/create_db.sql
